
int bang(int);
int test_bang(int);
int bitCount(int);
int test_bitCount(int);
int copyLSB(int);
int test_copyLSB(int);
int divpwr2(int, int);
int test_divpwr2(int, int);
int evenBits();
int test_evenBits();
int fitsBits(int, int);
int test_fitsBits(int, int);
int getByte(int, int);
int test_getByte(int, int);
int isGreater(int, int);
int test_isGreater(int, int);
int isNonNegative(int);
int test_isNonNegative(int);
int isNotEqual(int, int);
int test_isNotEqual(int, int);
int isPower2(int);
int test_isPower2(int);
int leastBitPos(int);
int test_leastBitPos(int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int satAdd(int, int);
int test_satAdd(int, int);
int tc2sm(int);
int test_tc2sm(int);
